# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sympa < Formula
  desc "Symmetric-only password store wrapping age"
  homepage "https://github.com/napalu/sympa"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/napalu/sympa/releases/download/v0.1.0/sympa_0.1.0_darwin_amd64.tar.gz"
      sha256 "5e672672d1e372ae55a1e490e36828b7a94e9db10377195a976950f1e5f74d33"

      define_method(:install) do
        bin.install "sympa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/napalu/sympa/releases/download/v0.1.0/sympa_0.1.0_darwin_arm64.tar.gz"
      sha256 "e1a5224d425c416fbaba9dbf003b5bc2409b801b2526f2d5a9caf4173292e25f"

      define_method(:install) do
        bin.install "sympa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/napalu/sympa/releases/download/v0.1.0/sympa_0.1.0_linux_amd64.tar.gz"
      sha256 "73ebe51467119a63f063b2ddf001191c68533835e9089281bdc554e15da145b2"
      define_method(:install) do
        bin.install "sympa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/napalu/sympa/releases/download/v0.1.0/sympa_0.1.0_linux_arm64.tar.gz"
      sha256 "1af227c5e7e0d0f2a4182ffa70800d195ff3c72f69129416a497bccaefbb6e46"
      define_method(:install) do
        bin.install "sympa"
      end
    end
  end

  test do
    system "#{bin}/sympa", "--version"
  end
end
