# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sympa < Formula
  desc "Symmetric-only password store wrapping age"
  homepage "https://github.com/napalu/sympa"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/napalu/sympa/releases/download/v0.2.0/sympa_0.2.0_darwin_amd64.tar.gz"
      sha256 "2ddfb14b451c3ec40c5667553ee294b1dbebc777c7db900c570fc6719f22f8b8"

      define_method(:install) do
        bin.install "sympa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/napalu/sympa/releases/download/v0.2.0/sympa_0.2.0_darwin_arm64.tar.gz"
      sha256 "bd56f7c476c74d1a101ed0e00acdcc9a3f3e7973415ea1021b5a1c1e0be9b257"

      define_method(:install) do
        bin.install "sympa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/napalu/sympa/releases/download/v0.2.0/sympa_0.2.0_linux_amd64.tar.gz"
      sha256 "bdd279025b687826850ecf881cd7c2dc11f722a8ed52103b2f904c10ec1d39a1"
      define_method(:install) do
        bin.install "sympa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/napalu/sympa/releases/download/v0.2.0/sympa_0.2.0_linux_arm64.tar.gz"
      sha256 "4beb3c4f746b4e2117088ed631d49977276c7a992b3a925c4f9502305a2bb817"
      define_method(:install) do
        bin.install "sympa"
      end
    end
  end

  test do
    system "#{bin}/sympa", "--version"
  end
end
